#!/bin/bash
## MANAGED BY ANSIBLE, DO NOT EDIT THIS FILE MANUALLY

# This script is used to find the Victron MPPT device connected via VE.Direct protocol and create a symbolic link to it at /dev/victron-mppt. 
# It scans for devices on /dev/ttyUSB* and checks for the presence of specific markers in the data read from the device to identify it as a VE.Direct device.

LINK_PATH="/dev/victron-mppt"
READ_TIMEOUT=1
MIN_MARKERS=3
SCAN_INTERVAL=300

log() {
    echo "[find-victron-mppt] $*"
}

match_vedirect_port() {
    local device=$1
    local raw_data
    local marker_count=0
    local marker

    [[ -c "${device}" && -r "${device}" ]] || return 1

    raw_data="$(timeout "${READ_TIMEOUT}" cat "${device}" 2>/dev/null || true)"
    raw_data="${raw_data//$'\r'/}"
    [[ -n "${raw_data}" ]] || return 1

    for marker in \
        '^PID[[:space:]]' \
        '^FW[[:space:]]' \
        '^SER#[[:space:]]' \
        '^V[[:space:]]' \
        '^CS[[:space:]]'; do
        if grep -qE "${marker}" <<< "${raw_data}"; then
            marker_count=$((marker_count + 1))
        fi
    done

    [[ ${marker_count} -ge ${MIN_MARKERS} ]]
}

main() {
    local device
    local found_device
    local Found

    
    Found=false
    while [[ $Found == false ]]; do
        found_device=

        for device in /dev/ttyUSB*; do
            [[ -e "${device}" ]] || break

            # Check if the device is allready in use by another process
            if fuser "${device}" >/dev/null 2>&1; then
                log "device ${device} is in use by another process, skipping"
                continue
            fi
            
            stty -F "${device}" 19200 raw

            if match_vedirect_port "${device}"; then
                found_device="${device}"
                break
            fi
        done

        if [[ -n "${found_device}" ]]; then
            if ! ln -sfn "${found_device}" "${LINK_PATH}"; then
                log "failed to link ${LINK_PATH} -> ${found_device}"
                return 2
            fi

            log "linked ${LINK_PATH} -> ${found_device}"
            Found=true
            return 0
        fi

        if [[ -L "${LINK_PATH}" ]]; then
            if ! rm -f "${LINK_PATH}"; then
                log "failed to remove stale link ${LINK_PATH}"
                return 3
            fi

            log "removed stale link ${LINK_PATH}"
        fi

        log "no VE.Direct device found on /dev/ttyUSB*"
        sleep "${SCAN_INTERVAL}"
    done
}

main "$@"