site_name: RecoveryBox Wiki
site_dir: wiki
site_url: http://recovery.box/wiki
repo_url: https://github.com/mr-dgidgi/recoverybox
hooks:
  - hooks/version_hook.py
repo_name: RecoveryBox
theme:
  name: material
  palette:
    # Day
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Passage en mode nuit
    # Night
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Passage en mode jour
  features:
    - navigation.tabs
extra_css:
  - stylesheets/recoverybox-theme.css

extra:
  alternate:
    - name: English
      link: /wiki/en/
      lang: en
    - name: Français
      link: /wiki/fr/
      lang: fr
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mr-dgidgi/recoverybox
      name: GitHub project

markdown_extensions:
  - admonition

plugins:
  - search
  - privacy:
      assets: true
      assets_fetch: true
      assets_fetch_dir: assets

nav:
  - Site officiel: "https://recoverybox.fr/"
  - Documentation (FR):
      - Accueil: fr/index.md
      - Démarrage rapide: fr/quickstart.md
      - Services:
          - Hotspot: fr/services/hotspot.md
          - Cartographie: fr/services/carto.md
          - Kiwix: fr/services/kiwix.md
          - Librairie: fr/services/library.md
          - Meshtastic: fr/services/meshtastic.md
          - OpenWebRX +: fr/services/owrx.md
          - Console: fr/services/console.md
          - Flatnotes: fr/services/flatnotes.md
      - admin:
          - Installation: fr/admin/install.md
          - Rbstatus: fr/admin/rbstatus.md
          - Generate-map: fr/admin/generate-map.md
          - Network-Configurator: fr/admin/network-configurator.md
          - Réseau: fr/admin/network.md
          - Meshtastic-Daemon: fr/admin/meshtastic-daemon.md
          - Outils système: fr/admin/system-tools.md
          - Debug: fr/admin/debug.md
          - Mise à jour (rb-update): fr/admin/rb-update.md
          - Variables Ansible: fr/admin/ansible-variables.md
  - Documentation (EN):
      - Home: en/index.md
      - Quickstart: en/quickstart.md
      - Services:
          - Hotspot: en/services/hotspot.md
          - Cartography: en/services/carto.md
          - Kiwix: en/services/kiwix.md
          - Library: en/services/library.md
          - Meshtastic: en/services/meshtastic.md
          - OpenWebRX +: en/services/owrx.md
          - Console: en/services/console.md
          - Flatnotes: en/services/flatnotes.md
      - admin:
          - Installation: en/admin/install.md
          - Rbstatus: en/admin/rbstatus.md
          - Generate-map: en/admin/generate-map.md
          - Network-Configurator: en/admin/network-configurator.md
          - Network: en/admin/network.md
          - Meshtastic-Daemon: en/admin/meshtastic-daemon.md
          - System Tools: en/admin/system-tools.md
          - Debug: en/admin/debug.md
          - Update (rb-update): en/admin/rb-update.md
          - Ansible Variables: en/admin/ansible-variables.md
