---
# renovate: datasource: github-releases depName: mr-dgidgi/rb-library
version_library: "1.0.1"
version_fonts: "master"
# renovate: datasource: git-tags depName: https://github.com/rtlsdrblog/rtl-sdr-blog
version_rtlsdr: "v1.3.6"
# renovate: datasource: docker depName: joeakeem/brouter
version_brouterContainer: "v1.7.9"
# renovate: datasource: github-releases depName: nrenner/brouter-web
version_brouterWeb: "0.18.1"
# renovate: datasource: docker depName: mrdgidgi/meshtastic-web-client
version_meshtasticWeb: "2.7.1"
# renovate: datasource: docker depName: ghcr.io/kiwix/kiwix-serve
version_kiwix: "3.8.2"
# renovate: datasource: docker depName: mrdgidgi/simple-hotspot
version_simpleHotspot: "1.0"
# renovate: datasource: docker depName: slechev/openwebrxplus-softmbe
version_owrx: "1.2.118"
# renovate: datasource: docker depName: maptiler/tileserver-gl
version_tileserver: "v5.6.0"
# renovate: datasource: docker depName: ghcr.io/onthegomap/planetiler
version_planetiler: "0.10.2"

interface_wlanAP: "wlanAP"
interface_wan: "Wan"
interface_lan: "Lan"

hotspot_conf :
  ssid: "recoverybox"
  password: "recoverybox"
  network: "192.168.200.0"
  mask: "24"
  ip: "192.168.200.1"
  dhcp_range_start: "192.168.200.100"
  dhcp_range_end: "192.168.200.200"

meshtastic_node:
  mac: "00:00:00:00:00:00"
  ip: "192.168.200.101"

kiwix_files:
  french: true
  english: true