#!/bin/bash
## MANAGED BY ANSIBLE, DO NOT EDIT THIS FILE MANUALLY

# Battery monitoring for laptops. This script is intended to be run as a cron job every minute.

OUTPUT_FILE='/data/www/battery.json'
BATTERY_LIST=()

get_batteries() {
    for dev in /sys/class/power_supply/*; do
        if [[ -f "$dev/type" ]] && [[ "$(cat "$dev/type")" == "Battery" ]]; then
            BATTERY_LIST+=("$dev")
        fi
    done
}

get_data() {

    BatteryName="$1"
    BatteryStatus=$(cat "$1/status")
    BatteryCapacity=$(cat "$1/capacity")
    BatteryPresent=$(cat "$1/present")
}

print_json() {

    cat <<EOF > "${OUTPUT_FILE}"
{
    "Values": [
EOF
    for Battery in "${BATTERY_LIST[@]}"; do
        if [[ "$Battery" != "${BATTERY_LIST[0]}" ]]; then
            End=","
        else
            End=""
        fi
        
        get_data "$Battery"

        if [[ "$BatteryPresent" -eq 1 ]]; then
            cat <<EOF >> "${OUTPUT_FILE}"
    {
        "Name": "${BatteryName}",
        "Status": "${BatteryStatus}",
        "Capacity": ${BatteryCapacity}
    }$End
EOF

        fi
    done
    cat <<EOF >> "${OUTPUT_FILE}"
    ],
    "Timestamp": $(date +%s),
    "Source": "rb-laptop"
}
EOF
}