#!/bin/bash
## MANAGED BY ANSIBLE, DO NOT EDIT THIS FILE MANUALLY

# Battery monitoring for laptops. This script is intended to be run as a cron job every minute.

OUTPUT_FILE='/data/www/battery.json'
BATTERY_LIST=()

get_batteries() {
    for dev in /sys/class/power_supply/*; do
        if [[ -f "$dev/type" ]] && [[ "$(cat "$dev/type")" == "Battery" ]]; then
            BATTERY_LIST+=("$dev")
        fi
    done
}

get_data() {

    BatteryName="$1"
    BatteryStatus=$(cat "$1/status")
    BatteryCapacity=$(cat "$1/capacity")
    BatteryPresent=$(cat "$1/present")
}

print_json() {

    cat <<EOF > "${OUTPUT_FILE}"
{
    "Values": [
EOF
    First=true
    for Battery in "${BATTERY_LIST[@]}"; do
        get_data "$Battery"
        if [[ "$BatteryPresent" -ne 1 ]]; then
            continue
        fi
        if [[ "$First" == "true" ]]; then
            First=false
        else
            echo "    ," >> "${OUTPUT_FILE}"

        cat <<EOF >> "${OUTPUT_FILE}"
    {
        "Name": "${BatteryName}",
        "Status": "${BatteryStatus}",
        "Capacity": ${BatteryCapacity}
    }
EOF

        fi
    done
    cat <<EOF >> "${OUTPUT_FILE}"
    ],
    "Timestamp": $(date +%s),
    "Source": "rb-laptop"
}
EOF
}

main() {
    get_batteries
    print_json
}

main