---
- name: Pull meshtastic-web docker image
  community.docker.docker_image:
    name: mrdgidgi/meshtastic-web-client
    tag: "{{ version_meshtasticWeb }}"
    source: pull

- name: Create meshtastic-web service
  ansible.builtin.template:
    src: etc/systemd/system/meshtastic-web.service.j2
    dest: /etc/systemd/system/meshtastic-web.service
    owner: root
    group: root
    mode: '0644'

- name : Create meshtastic-web apache2 site
  ansible.builtin.copy:
    src: etc/apache2/sites-available/meshtastic-web.conf
    dest: /etc/apache2/sites-available/meshtastic-web.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable meshtastic-web site
  ansible.builtin.apache2_site:
    name: meshtastic-web.conf
    state: enabled

- name: Enable meshtastic-web service
  ansible.builtin.systemd:
    name: meshtastic-web
    daemon_reload: yes
    enabled: yes
    state: started