---
- name: Create /data/library directory
  ansible.builtin.file:
    path: /data/library
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: clone library repository
  ansible.builtin.git:
    repo: "{{ library_repo }}"
    dest: /data/library
    version: "{{ version_library }}"
    force: yes

- name: Create /data/library/PDF/custom directory
  ansible.builtin.file:
    path: /data/library/PDF/custom
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create library apache2 site
  ansible.builtin.copy:
    src: etc/apache2/sites-available/library.conf
    dest: /etc/apache2/sites-available/library.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable library site
  ansible.builtin.apache2_site:
    name: library.conf
    state: enabled

- name: Reload apache2 service
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded
    