---

- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: present

- name: Enable proxy modules
  ansible.builtin.apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http
    - proxy_wstunnel
    - rewrite

- name: create /data/www directory
  ansible.builtin.file:
    path: /data/www
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create index.html
  ansible.builtin.copy:
    src: data/www/index.html
    dest: /data/www/index.html
    owner: root
    group: root
    mode: '0644'

- name: Create recovery.box site
  ansible.builtin.copy:
    src: etc/apache2/sites-available/000-www.conf
    dest: /etc/apache2/sites-available/000-www.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable recovery.box site
  ansible.builtin.apache2_site:
    name: 000-www.conf
    state: enabled

- name: Disable default site
  ansible.builtin.apache2_site:
    name: 000-default.conf
    state: disabled

- name: Enable apache2 service
  ansible.builtin.systemd_service:
    name: apache2
    enabled: true
    state: restarted