---
- name: Setup Environment
  ansible.builtin.import_tasks: setup_environment.yml
  tags:
    - setup_environment

- name: Deploy Network tools
  ansible.builtin.import_tasks: deploy_network.yml
  tags:
    - deploy_network
