#!/bin/bash
## MANAGED BY ANSIBLE, DO NOT EDIT THIS FILE MANUALLY


OUTPUT_PATH="/data/brouter/www/recoverybox.json"
TEMP_PATH="${OUTPUT_PATH}.tmp"

# check if gpspipe is available and if a GPS is connected
if ! command -v gpspipe &> /dev/null; then
    echo "gpspipe command not found. Please install gpsd and gpsd-clients."
    exit 1
fi
GPSConnected=$(timeout 3s gpspipe -w -n 5 2>/dev/null | grep -c "TPV" 2>/dev/null)
if [ "$GPSConnected" -eq 0 ]; then
    echo "No GPS device connected or gpsd is not running."
    exit 1
fi

#check if brouter is running
if ! systemctl is-active --quiet brouter; then
    exit 1
fi

GPSData=$(timeout 3s gpspipe -w -n 5 2>/dev/null | grep "TPV" | tail -n 1)
if [[ -z "$GPSData" ]]; then
    mode=0
    Lat=""
    Lon=""
else
    mode=$(echo "$GPSData" | jq -r '.mode' 2>/dev/null || echo 0)
    Lat=$(echo "$GPSData" | jq -r '.lat' 2>/dev/null || echo "")
    Lon=$(echo "$GPSData" | jq -r '.lon' 2>/dev/null || echo "")
fi

if [[ ! -z "$Lat" && ! -z "$Lon" && "$mode" -ge 2 ]]; then
    # update json file with gps data
    jq -n \
        --arg lat "$Lat" \
        --arg lon "$Lon" \
        '{
            "type": "FeatureCollection",
            "features": [
            {
                "type": "Feature",
                "geometry": {
                "type": "Point",
                "coordinates": [($lon|tonumber), ($lat|tonumber)]
                },
                "properties": {
                "name": "RecoveryBox",
                "description": "Hotspot location",
                "icon": "server"
                }
            }
            ]
        }' > "$TEMP_PATH"
    mv "$TEMP_PATH" "$OUTPUT_PATH"
fi