---
- name: Create iptables directory
  ansible.builtin.file:
    path: /etc/iptables
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create iptables script
  ansible.builtin.copy:
    src: etc/iptables/iptables.sh
    dest: /etc/iptables/iptables.sh
    owner: root
    group: root
    mode: '0755'

- name: Create iptables service
  ansible.builtin.copy:
    src: etc/systemd/system/iptables.service
    dest: /etc/systemd/system/iptables.service
    owner: root
    group: root
    mode: '0644'

- name: Enable iptables service
  ansible.builtin.systemd_service:
    name: iptables
    enabled: true
    daemon_reload: true
    state: restarted
  when: "'dry_run' not in ansible_run_tags"

- name: Enable ipv4 routing
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true
  when: "'dry_run' not in ansible_run_tags"

- name: Disable linkdown routing
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.ignore_routes_with_linkdown
    value: '1'
    state: present
    reload: true
  when: "'dry_run' not in ansible_run_tags"
