---
- name: Get brouter files index
  ansible.builtin.uri:
    url: "https://brouter.de/brouter/segments4/"
    return_content: true
  register: recoverybox_brouter_index

- name: Build rd5 file list
  ansible.builtin.set_fact:
    recoverybox_brouter_rd5_files: "{{ recoverybox_brouter_index.content | regex_findall('href=\"([^\"]+\\.rd5)\"') | unique }}"

- name: Download brouter rd5 files
  ansible.builtin.get_url:
    url: "https://brouter.de/brouter/segments4/{{ item }}"
    dest: "/data/brouter/segments4/{{ item }}"
    mode: '0644'
    force: true
  loop: "{{ recoverybox_brouter_rd5_files }}"
