---
- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository in DEB822 format
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: [https://download.docker.com/linux/debian]
    suites: ["{{ ansible_facts['distribution_release'] }}"]
    components: [stable]
    architectures: ["{{ ansible_facts['architecture'] if ansible_facts['architecture'] != 'x86_64' else 'amd64' }}"]
    signed_by: /etc/apt/keyrings/docker.asc

- name: Install Docker packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Enable Docker service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: restarted
  when: "'dry_run' not in ansible_run_tags"
