---
- name: Create /data/library directory
  ansible.builtin.file:
    path: /data/library
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone library repository
  ansible.builtin.git:
    repo: "https://github.com/mr-dgidgi/rb-library.git"
    dest: /data/library
    version: "{{ recoverybox_version_library }}"
    force: true

- name: Create /data/library/PDF/custom directory
  ansible.builtin.file:
    path: /data/library/PDF/custom
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create library apache2 site
  ansible.builtin.copy:
    src: etc/apache2/sites-available/library.conf
    dest: /etc/apache2/sites-available/library.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable library site
  ansible.builtin.command:
    cmd: a2ensite library.conf
  changed_when: false

- name: Reload apache2 service
  ansible.builtin.systemd_service:
    name: apache2
    state: reloaded
