---
- name: Create Kiwix directory
  ansible.builtin.file:
    path: /data/kiwix
    state: directory
    mode: '0755'

- name: Download Kiwix container
  community.docker.docker_image:
    name: ghcr.io/kiwix/kiwix-serve
    tag: "{{ recoverybox_version_kiwix }}"
    source: pull

- name: Create Kiwix service
  ansible.builtin.template:
    src: etc/systemd/system/kiwix.service.j2
    dest: /etc/systemd/system/kiwix.service
    owner: root
    group: root
    mode: '0644'

- name: Enable Kiwix service
  ansible.builtin.systemd_service:
    name: kiwix
    enabled: true
    daemon_reload: true
    state: started
  when: "'dry_run' not in ansible_run_tags"
