---
- name: Pull meshtastic-web docker image
  community.docker.docker_image:
    name: mrdgidgi/meshtastic-web-client
    tag: "{{ recoverybox_version_meshtastic_web }}"
    source: pull

- name: Create meshtastic-web service
  ansible.builtin.template:
    src: etc/systemd/system/meshtastic-web.service.j2
    dest: /etc/systemd/system/meshtastic-web.service
    owner: root
    group: root
    mode: '0644'

- name: Create meshtastic-web apache2 site
  ansible.builtin.copy:
    src: etc/apache2/sites-available/meshtastic-web.conf
    dest: /etc/apache2/sites-available/meshtastic-web.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable meshtastic-web site
  ansible.builtin.command:
    cmd: a2ensite meshtastic-web.conf
  changed_when: false

- name: Enable meshtastic-web service
  ansible.builtin.systemd_service:
    name: meshtastic-web
    daemon_reload: true
    enabled: true
    state: started
