---
- name: Install Brouter
  when:
    - recoverybox_enable_brouter
    - recoverybox_enable_apache
  block:
    - name: Pull brouter container
      community.docker.docker_image:
        name: "joeakeem/brouter"
        tag: "{{ recoverybox_version_brouter_container }}"
        source: pull

    - name: Create /data/brouter/ directories
      ansible.builtin.file:
        path: "/data/brouter/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - segments4
        - www
        - profiles

    - name: Create brouter service
      ansible.builtin.template:
        src: etc/systemd/system/brouter.service.j2
        dest: /etc/systemd/system/brouter.service
        owner: root
        group: root
        mode: '0644'

    - name: Download brouter-web
      ansible.builtin.unarchive:
        src: "https://github.com/nrenner/brouter-web/releases/download/{{ recoverybox_version_brouter_web }}/brouter-web.{{ recoverybox_version_brouter_web }}.zip" # noqa: yaml[line-length]
        dest: /data/brouter/www
        remote_src: true
        mode: '0755'

    - name: Custom brouter-config.js
      ansible.builtin.copy:
        src: data/brouter/www/config.js
        dest: /data/brouter/www/config.js
        owner: root
        group: root
        mode: '0644'

    - name: Add brouter profiles
      ansible.builtin.copy:
        src: data/brouter/profiles/
        dest: /data/brouter/profiles/
        owner: root
        group: root
        mode: '0644'
      loop:
        - car-fast.brf
        - lookups.dat
        - car-offroad.brf

    - name: Customize translation FR
      ansible.builtin.lineinfile:
        path: /data/brouter/www/dist/locales/fr.json
        regexp: '      "vm-forum-liegerad-schnell": "Vélo couché (rapide)",'
        line: '      "car-offroad": "4x4 (hors route)",'

    - name: Customize translation EN
      ansible.builtin.lineinfile:
        path: /data/brouter/www/dist/locales/en.json
        regexp: '      "vm-forum-liegerad-schnell": "Vélo couché (rapide)",'
        line: '      "car-offroad": "4x4 (off road)",'

    - name: Add GPS javascript to brouter-web
      ansible.builtin.copy:
        src: data/brouter/www/recoverybox-gps.js
        dest: /data/brouter/www/recoverybox-gps.js
        owner: root
        group: root
        mode: '0644'

    - name: Add GPS bash script for brouter-web
      ansible.builtin.copy:
        src: data/brouter/gps-to-json.sh
        dest: /data/brouter/gps-to-json.sh
        owner: root
        group: root
        mode: '0755'

    - name: Custom index.html to include GPS javascript
      ansible.builtin.lineinfile:
        path: /data/brouter/www/index.html
        insertbefore: '</body>'
        line: '\t<script src="recoverybox-gps.js"></script>'

    - name: Create brouter apache2 site
      ansible.builtin.template:
        src: etc/apache2/sites-available/carto.conf.j2
        dest: /etc/apache2/sites-available/carto.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable carto site
      ansible.builtin.command:
        cmd: a2ensite carto.conf
      changed_when: false

    - name: Reload apache2 service
      ansible.builtin.systemd_service:
        name: apache2
        state: reloaded
      when: "'dry_run' not in ansible_run_tags"

    - name: Enable brouter service
      ansible.builtin.systemd_service:
        name: brouter
        enabled: "{{ recoverybox_enable_brouter }}"
        daemon_reload: true
        state: started
      when: "'dry_run' not in ansible_run_tags"

- name: Deactivate Brouter
  when: not recoverybox_enable_brouter or not recoverybox_enable_apache
  block:
    - name: Check if carto.conf file exists
      ansible.builtin.stat:
        path: /etc/apache2/sites-available/carto.conf
      register: recoverybox_apache_file

    - name: Disable carto site
      ansible.builtin.command:
        cmd: a2dissite carto.conf
      changed_when: false
      when: recoverybox_apache_file.stat.exists

    - name: Disable brouter service
      ansible.builtin.systemd_service:
        name: brouter
        enabled: "{{ recoverybox_enable_brouter }}"
        state: stopped
      when:
        - "'dry_run' not in ansible_run_tags"
        - "'brouter.service' in ansible_facts.services"
