---
- name: Set GPSD options
  ansible.builtin.lineinfile:
    path: /etc/default/gpsd
    regexp: '^GPSD_OPTIONS=""'
    line: 'GPSD_OPTIONS="-n"'
    state: present

- name: Restart GPSD service
  ansible.builtin.systemd_service:
    name: gpsd
    enabled: true
    state: started
  when: "'dry_run' not in ansible_run_tags"

- name: Set GPS for Chrony
  ansible.builtin.copy:
    src: etc/chrony/000-gps.conf
    dest: /etc/chrony/000-gps.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart Chrony service
  ansible.builtin.systemd_service:
    name: chrony
    enabled: true
    state: started
  when: "'dry_run' not in ansible_run_tags"

- name: Copy rb-laptop script
  ansible.builtin.copy:
    src: etc/rb-laptop/rb-laptop.sh
    dest: /etc/rb-laptop/rb-laptop.sh
    owner: root
    group: root
    mode: '0755'
  when: not recoverybox_enable_victron

- name: Copy rb-laptop cron file
  ansible.builtin.copy:
    src: etc/cron.d/rb-laptop
    dest: /etc/cron.d/rb-laptop
    owner: root
    group: root
    mode: '0644'
  when: not recoverybox_enable_victron
