---
# renovate: datasource=github-releases depName=mr-dgidgi/rb-library
recoverybox_version_library: "1.1.0"
recoverybox_version_fonts: "master"
# renovate: datasource=git-tags depName=https://github.com/rtlsdrblog/rtl-sdr-blog
recoverybox_version_rtlsdr: "v1.3.6"
# renovate: datasource=docker depName=joeakeem/brouter
recoverybox_version_brouter_container: "v1.7.9"
# renovate: datasource=github-releases depName=nrenner/brouter-web
recoverybox_version_brouter_web: "0.18.1"
# renovate: datasource=docker depName=mrdgidgi/meshtastic-web-client
recoverybox_version_meshtastic_web: "2.7.1"
# renovate: datasource=github-releases depName=meshtastic/python
recoverybox_version_meshtastic_python: "2.7.11"
# renovate: datasource=docker depName=ghcr.io/kiwix/kiwix-serve
recoverybox_version_kiwix: "3.8.2"
# renovate: datasource=docker depName=mrdgidgi/simple-hotspot
recoverybox_version_simple_hotspot: "1.0"
# renovate: datasource=docker depName=slechev/openwebrxplus-softmbe
recoverybox_version_owrx: "1.2.120"
# renovate: datasource=docker depName=maptiler/tileserver-gl
recoverybox_version_tileserver: "v5.6.0"
# renovate: datasource=docker depName=ghcr.io/onthegomap/planetiler
recoverybox_version_planetiler: "0.10.2"
# renovate: datasource=docker depName=dullage/flatnotes
recoverybox_version_flatnotes: "v5.5.4"


# Enable services on demand
recoverybox_enable_apache: true
recoverybox_enable_library: true
recoverybox_enable_owrx: true
recoverybox_enable_brouter: true
recoverybox_enable_tileserver: true
recoverybox_enable_cockpit: true
recoverybox_enable_kiwix: true
recoverybox_enable_meshtastic: true
recoverybox_enable_hotspot: true
recoverybox_enable_flatnotes: true
recoverybox_enable_victron: false

# Activate HTTPS
recoverybox_enable_https: false

# OpenWebRX credentials
recoverybox_owrx_conf:
  username: "recoverybox"
  password: "recoverybox"

# Network interfaces
recoverybox_interface_wlanap: "wlanAP"
recoverybox_interface_wan: "Wan"
recoverybox_interface_lan: "Lan"

# Hotspot configuration
recoverybox_hotspot_conf:
  ssid: "recoverybox"
  password: "recoverybox"
  mode: "g" # 2.4GHz : g or b (legacy), 5GHz/6GHz : a, acs if supported by the card
  channel: "11" # 2.4GHz : 1/7/11, 5GHz : 36-165, 6GHz : 1-233, 0 or acs if supported by the card
  auth_algs: "1"
  wpa: "2"
  wpa_key_mgmt: "WPA-PSK"
  wpa_pairwise: "TKIP CCMP"
  rsn_pairwise: "CCMP"
  network: "192.168.200.0"
  mask: "24"
  ip: "192.168.200.1"
  dhcp_range_start: "192.168.200.100"
  dhcp_range_end: "192.168.200.200"


# fill this if you have a meshtastic node to connect to
recoverybox_meshtastic_node:
  mac: "00:00:00:00:00:00"
  ip: "192.168.200.101"

# kiwix files to download, see https://lb.download.kiwix.org/zim/
recoverybox_kiwix_files:
  - category: wikipedia
    language: fr
    enable: true
    arg: "all_nopic" # all_mini,all_nopic,all_maxi
  - category: wikipedia
    language: en
    enable: true
    arg: "all_nopic" # all_mini,all_nopic,all_maxi
#  - category: maps
#    language: en
#    enable: true
#    arg: "croatia"


# Allow to download segment4 files for brouter
recoverybox_download_brouter: true
# Allow to download world.mbtiles for tileserver-gl
recoverybox_download_mbtiles: true

# Flatnotes type of conf
recoverybox_flatnotes_open: "full" # open, secure, full
recoverybox_flatnotes_secure:
  username: "recadmin"
  password: "RecoveryAdmin"
  secret_key: "aLongRandomSeriesOfCharacters123"


recoverybox_brouter_rename:
  fr:
    car_offroad:
      old: '      "vm-forum-liegerad-schnell": "Vélo couché (rapide)",'
      new: '      "car-offroad": "4x4 (hors route)",'
    gravel:
      old: '      "moped": "Mobylette",'
      new: '      "gravel": "Vélo Tout Chemin",'
    wet:
      old: '      "river": "Fluvial",'
      new: '      "walking-wet": "marche (Humide)",'
  en:
    car_offroad:
      old: '      "vm-forum-liegerad-schnell": "Recumbent bike (fast)",'
      new: '      "car-offroad": "4x4 (off-road)",'
    gravel:
      old: '      "moped": "Moped",'
      new: '      "gravel": "Gravel bike",'
    wet:
      old: '      "river": "River",'
      new: '      "walking-wet": "Walking (wet)",'
